name: Build & Deploy

on:
  push:
    branches: [ main ]
permissions:
  contents: write 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) 소스 체크아웃
      - uses: actions/checkout@v4

      # 2) Docker Hub 로그인
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Docker 이미지 빌드 & 푸시
      - name: Build & Push Docker Image
        run: |
          TAG=${{ github.sha }}
          IMAGE=${{ vars.DOCKERHUB_USERNAME }}/blog:${TAG}
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      # 4) deployment.yaml 이미지 태그 변경
      - name: Update Deployment Tag
        run: |
          pip install yq -q
          yq -i -y '.spec.template.spec.containers[0].image = "wngud1/blog:${{ env.IMAGE_TAG }}"' cd/deployment.yaml
          git config user.name "gha-bot"
          git config user.email "[email protected]"
          git commit -am "chore: bump image to ${{ env.IMAGE_TAG }}"
          git push
